### ISSUE TITLE
code

### ISSUE THREAD

**Issue by z744364418p** [wentaozhu/DeepEM-for-Weakly-Supervised-Detection#2]
code？

**Comment by wentaozhu** [comment]
Thank you very much for your interest! We will upload the code this weekends when I am free. Will notify you then.

**Comment by mowen9** [comment]
@wentaozhu We are looking forward to your code.

**Comment by wentaozhu** [comment]
Thank you very much for your interest! I am very sorry that I am very busy. I will upload my code and scripts this weekends. Thank you very much for your patience!

**Comment by wentaozhu** [comment]
You guys can get to know the idea of DeepEM now. I have added the scripts into the repository. Thank you very much for your interest! @z744364418p @mowen9

**Comment by mowen9** [comment]
@wentaozhu Thanks!
