### ISSUE TITLE
Quick question with the file calibweaklabelallsmall.csv

### ISSUE THREAD

**Issue by waterdeepmage** [wentaozhu/DeepEM-for-Weakly-Supervised-Detection#3]
Hi, wentao,

First, thanks very much for making the code open source.

Can you explain what do the lowz, upz, dataz, datax, and datay represent in your calibweaklabelallsmall.csv file?

I understand position means the loc (right upper lobe, right middle lobe, etc). centerslice should mean zm (the location of the slice where the weak labelled nodules are). why would you also have datax, datay, and dataz? What do they represent? 

Thanks.

**Comment by wentaozhu** [comment]
Thank you very much for your interest! It is the total size of the CT image.

**Comment by waterdeepmage** [comment]
Wentao, are the annotations in calibweaklabelallsmall.csv on the original CT images or are they on the pre-processed images (aka, cropped as sub-volume for lungs, resampled to another resolution) after prepare.py?

**Comment by wentaozhu** [comment]
I think it is pre-processed. In our paper, we said, it is pre-processed so that it is more accurate.
